# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from datanode.src.protos import datanode_pb2 as datanode_dot_src_dot_protos_dot_datanode__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DataNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Push = channel.unary_unary(
                '/datanode.DataNode/Push',
                request_serializer=datanode_dot_src_dot_protos_dot_datanode__pb2.PushRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Pull = channel.unary_unary(
                '/datanode.DataNode/Pull',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=datanode_dot_src_dot_protos_dot_datanode__pb2.PullResponse.FromString,
                )
        self.AcknowledgePull = channel.unary_unary(
                '/datanode.DataNode/AcknowledgePull',
                request_serializer=datanode_dot_src_dot_protos_dot_datanode__pb2.AcknowledgePullRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ReadPartition = channel.unary_stream(
                '/datanode.DataNode/ReadPartition',
                request_serializer=datanode_dot_src_dot_protos_dot_datanode__pb2.ReadPartitionRequest.SerializeToString,
                response_deserializer=datanode_dot_src_dot_protos_dot_datanode__pb2.ReadPartitionResponse.FromString,
                )
        self.WritePartition = channel.stream_unary(
                '/datanode.DataNode/WritePartition',
                request_serializer=datanode_dot_src_dot_protos_dot_datanode__pb2.WritePartitionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.PurgeReplicaData = channel.unary_unary(
                '/datanode.DataNode/PurgeReplicaData',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.IsHealthy = channel.unary_unary(
                '/datanode.DataNode/IsHealthy',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetRemainingMessagesCount = channel.unary_unary(
                '/datanode.DataNode/GetRemainingMessagesCount',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=datanode_dot_src_dot_protos_dot_datanode__pb2.GetRemainingMessagesCountResponse.FromString,
                )


class DataNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Push(self, request, context):
        """Basic Queue Operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pull(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgePull(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPartition(self, request, context):
        """Data syncing Operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WritePartition(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeReplicaData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsHealthy(self, request, context):
        """Cluster consensus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRemainingMessagesCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=datanode_dot_src_dot_protos_dot_datanode__pb2.PushRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Pull': grpc.unary_unary_rpc_method_handler(
                    servicer.Pull,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=datanode_dot_src_dot_protos_dot_datanode__pb2.PullResponse.SerializeToString,
            ),
            'AcknowledgePull': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgePull,
                    request_deserializer=datanode_dot_src_dot_protos_dot_datanode__pb2.AcknowledgePullRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReadPartition': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadPartition,
                    request_deserializer=datanode_dot_src_dot_protos_dot_datanode__pb2.ReadPartitionRequest.FromString,
                    response_serializer=datanode_dot_src_dot_protos_dot_datanode__pb2.ReadPartitionResponse.SerializeToString,
            ),
            'WritePartition': grpc.stream_unary_rpc_method_handler(
                    servicer.WritePartition,
                    request_deserializer=datanode_dot_src_dot_protos_dot_datanode__pb2.WritePartitionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PurgeReplicaData': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeReplicaData,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'IsHealthy': grpc.unary_unary_rpc_method_handler(
                    servicer.IsHealthy,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetRemainingMessagesCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRemainingMessagesCount,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=datanode_dot_src_dot_protos_dot_datanode__pb2.GetRemainingMessagesCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datanode.DataNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datanode.DataNode/Push',
            datanode_dot_src_dot_protos_dot_datanode__pb2.PushRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datanode.DataNode/Pull',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            datanode_dot_src_dot_protos_dot_datanode__pb2.PullResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcknowledgePull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datanode.DataNode/AcknowledgePull',
            datanode_dot_src_dot_protos_dot_datanode__pb2.AcknowledgePullRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadPartition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/datanode.DataNode/ReadPartition',
            datanode_dot_src_dot_protos_dot_datanode__pb2.ReadPartitionRequest.SerializeToString,
            datanode_dot_src_dot_protos_dot_datanode__pb2.ReadPartitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WritePartition(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/datanode.DataNode/WritePartition',
            datanode_dot_src_dot_protos_dot_datanode__pb2.WritePartitionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurgeReplicaData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datanode.DataNode/PurgeReplicaData',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsHealthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datanode.DataNode/IsHealthy',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRemainingMessagesCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datanode.DataNode/GetRemainingMessagesCount',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            datanode_dot_src_dot_protos_dot_datanode__pb2.GetRemainingMessagesCountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
