global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['node_exporter:9100']
  - targets: ['leader_0:9000']
  - targets: ['leader_1:9000']
  - targets: ['datanode_0:9000']
  - targets: ['datanode_1:9000']
  - targets: ['datanode_2:9000']
  - targets: ['datanode_3:9000']