// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/queue/queue.proto

package queue

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                [][]byte `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f19f82a9e8d3cfaf, []int{0}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PushRequest) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PullResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                [][]byte `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f19f82a9e8d3cfaf, []int{1}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PullResponse) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type AcknowledgePullRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcknowledgePullRequest) Reset()         { *m = AcknowledgePullRequest{} }
func (m *AcknowledgePullRequest) String() string { return proto.CompactTextString(m) }
func (*AcknowledgePullRequest) ProtoMessage()    {}
func (*AcknowledgePullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f19f82a9e8d3cfaf, []int{2}
}

func (m *AcknowledgePullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcknowledgePullRequest.Unmarshal(m, b)
}
func (m *AcknowledgePullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcknowledgePullRequest.Marshal(b, m, deterministic)
}
func (m *AcknowledgePullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcknowledgePullRequest.Merge(m, src)
}
func (m *AcknowledgePullRequest) XXX_Size() int {
	return xxx_messageInfo_AcknowledgePullRequest.Size(m)
}
func (m *AcknowledgePullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcknowledgePullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcknowledgePullRequest proto.InternalMessageInfo

func (m *AcknowledgePullRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*PushRequest)(nil), "queue.PushRequest")
	proto.RegisterType((*PullResponse)(nil), "queue.PullResponse")
	proto.RegisterType((*AcknowledgePullRequest)(nil), "queue.AcknowledgePullRequest")
}

func init() {
	proto.RegisterFile("api/queue/queue.proto", fileDescriptor_f19f82a9e8d3cfaf)
}

var fileDescriptor_f19f82a9e8d3cfaf = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xd1, 0x4b, 0xc3, 0x30,
	0x10, 0xc6, 0xa9, 0xb3, 0x82, 0x71, 0xa0, 0x44, 0x1d, 0xa3, 0x22, 0x8c, 0x3d, 0x8d, 0x21, 0x09,
	0x6c, 0xe8, 0xbb, 0x82, 0xe0, 0x8b, 0xb0, 0x15, 0x9f, 0x7c, 0x6b, 0xb7, 0x33, 0x1b, 0xbd, 0x2d,
	0x59, 0x93, 0x53, 0xfa, 0xaf, 0xf9, 0xd7, 0x49, 0x1a, 0x95, 0x22, 0x16, 0xf6, 0x12, 0x72, 0xc9,
	0x7d, 0xf7, 0x7d, 0x3f, 0x8e, 0x5d, 0x66, 0x66, 0x2d, 0x77, 0x04, 0x04, 0xe1, 0x14, 0xa6, 0xd4,
	0x4e, 0xf3, 0xb8, 0x2e, 0x92, 0x2b, 0xa5, 0xb5, 0x42, 0x90, 0xf5, 0x63, 0x4e, 0x6f, 0x12, 0x36,
	0xc6, 0x55, 0xa1, 0x67, 0x78, 0xcb, 0x4e, 0x66, 0x64, 0x57, 0x29, 0xec, 0x08, 0xac, 0xe3, 0x67,
	0xac, 0x53, 0x40, 0xd5, 0x8f, 0x06, 0xd1, 0xe8, 0x38, 0xf5, 0x57, 0x7e, 0xc1, 0xe2, 0xf7, 0x0c,
	0x09, 0xfa, 0x07, 0x83, 0xce, 0xa8, 0x9b, 0x86, 0x62, 0x78, 0xc7, 0xba, 0x33, 0x42, 0x4c, 0xc1,
	0x1a, 0xbd, 0xb5, 0xb0, 0xb7, 0x6e, 0xcc, 0x7a, 0xf7, 0x8b, 0x62, 0xab, 0x3f, 0x10, 0x96, 0x0a,
	0xc2, 0x88, 0x16, 0xe7, 0xc9, 0x67, 0xc4, 0xe2, 0xb9, 0x27, 0xe0, 0x13, 0x76, 0xe8, 0x43, 0x72,
	0x2e, 0x02, 0x5e, 0x23, 0x71, 0xd2, 0x13, 0x01, 0x4f, 0xfc, 0xe0, 0x89, 0x47, 0x8f, 0xc7, 0xa7,
	0x5e, 0x83, 0xc8, 0x5b, 0xfe, 0x93, 0xf3, 0xdf, 0x59, 0x0d, 0x8c, 0x27, 0x76, 0xfa, 0x27, 0x1e,
	0xbf, 0xfe, 0xee, 0xfb, 0x3f, 0x76, 0x9b, 0xfd, 0xc3, 0xcd, 0xeb, 0x58, 0xad, 0xdd, 0x8a, 0x72,
	0xb1, 0xd0, 0x1b, 0x59, 0x54, 0xb6, 0x04, 0xf9, 0x42, 0xa5, 0x43, 0x78, 0x9e, 0x4b, 0x84, 0x6c,
	0x09, 0xa5, 0x34, 0x85, 0x0a, 0xfb, 0xca, 0x8f, 0x6a, 0xf5, 0xf4, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0x5e, 0x1a, 0xb3, 0xe0, 0xc9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QueueClient is the client API for Queue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueueClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Pull(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PullResponse, error)
	AcknowledgePull(ctx context.Context, in *AcknowledgePullRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type queueClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueClient(cc grpc.ClientConnInterface) QueueClient {
	return &queueClient{cc}
}

func (c *queueClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/queue.Queue/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) Pull(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PullResponse, error) {
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, "/queue.Queue/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueClient) AcknowledgePull(ctx context.Context, in *AcknowledgePullRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/queue.Queue/AcknowledgePull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServer is the server API for Queue service.
type QueueServer interface {
	Push(context.Context, *PushRequest) (*empty.Empty, error)
	Pull(context.Context, *empty.Empty) (*PullResponse, error)
	AcknowledgePull(context.Context, *AcknowledgePullRequest) (*empty.Empty, error)
}

// UnimplementedQueueServer can be embedded to have forward compatible implementations.
type UnimplementedQueueServer struct {
}

func (*UnimplementedQueueServer) Push(ctx context.Context, req *PushRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (*UnimplementedQueueServer) Pull(ctx context.Context, req *empty.Empty) (*PullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (*UnimplementedQueueServer) AcknowledgePull(ctx context.Context, req *AcknowledgePullRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgePull not implemented")
}

func RegisterQueueServer(s *grpc.Server, srv QueueServer) {
	s.RegisterService(&_Queue_serviceDesc, srv)
}

func _Queue_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).Pull(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queue_AcknowledgePull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServer).AcknowledgePull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queue.Queue/AcknowledgePull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServer).AcknowledgePull(ctx, req.(*AcknowledgePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Queue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "queue.Queue",
	HandlerType: (*QueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Queue_Push_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _Queue_Pull_Handler,
		},
		{
			MethodName: "AcknowledgePull",
			Handler:    _Queue_AcknowledgePull_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/queue/queue.proto",
}
