{
 "title": "TurtleMQ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "percentile", "label": "Percentile", "query": "0.9, 0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Leader RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(leader_total_bucket{}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Leader Latency Percentile-${percentile}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(leader_latency_bucket{}[1m])) by (le, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Datanode Push RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(push_throughput_bucket{}[1m])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Datanode Push Latency Percentile-${percentile}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(push_latency_bucket{}[1m])) by (le, provider))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Datanode Pull RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pull_throughput_bucket{}[1m])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Datanode Pull Latency Percentile-${percentile}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(pull_latency_bucket{}[1m])) by (le, provider))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Datanode Ack RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ack_throughput_bucket{}[1m])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Datanode Ack Latency Percentile-${percentile}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${percentile}, sum(rate(ack_latency_bucket{}[1m])) by (le, provider))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(message_count{}[1m])) by (provider) ",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Message Per Datanode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "message_count{}", "legendFormat": "{{provider}}" }
   ]
  },
  {
   "title": "Datanode Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(disk_used_size{}[1m])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Number of leader go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(go_goroutines{}[1m]))",
     "legendFormat": "Leader Goroutines"
    }
   ]
  }
 ]
}