name: deploy

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to DO
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: turtlemq
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
