name: go-test
on: [push]
jobs:

  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:

      - name: Download Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        working-directory: ./leader
        run: |
          go get -v -t -d ./...        

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        working-directory: ./leader
        run: go build -o $@ leader ./cmd/$@

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        working-directory: ./leader
        run: go test -v ./...
