name: Test
on: [ push ]

jobs:
  Go:
    name: Leader Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        id: go

      - name: Install dependencies
        working-directory: ./leader
        run: |
          go get -v -t -d ./...        

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        working-directory: ./leader
        run: go build -o $@ leader ./cmd/$@

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        working-directory: ./leader
        run: go test -v ./...

  Python:
    name: Datanode Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./datanode
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        working-directory: ./datanode/src
        run: python -m unittest unit_tests.py
